### ISSUE TITLE
Random V 2.0 task items

### ISSUE THREAD

**Issue by cartazio** [haskell/random#31] opened 2015-12-08 23:52 UTC
based up on the lovely GSOC work by  @nkartashov at https://github.com/nkartashov/SplitMix (and associated repos https://github.com/nkartashov/htestu for big crush/small crush statistical validation along and then https://github.com/nkartashov/prng-bench for performance comparison), @zaxtax and I are starting some planning work for Random Version 2.0
(and fyi to @idontgetoutmuch @gbaz et al)  

let it be known
1) based upon experimental data thus far, splitmix  (subject to certain caveats that are mostly around bad seed subsets that can be easily addressed by porting applicable machinery from the java sibling and possibly pestering guy steele as suggested  by some folks at oracle labs i spoke with this week), splitmix is the only rng aside from PCG-Random implemented in haskell that has a sequential `next` operation that passes big crush
2) splitmix is the only RNG we know of implemented in haskell that supports a  `split` operation that passes big crush when used as the sequencing operation 
(i need to do further auditing of how those crush tests were setup, but thats another sub item)

the following (approximate) task items, in part leveraging the excellent work by @nkartashov should form the foundation for prepping a v2 of random 
- [ ] have fast gen float / double siblings (theres fast ways to generate unit interval floats, and unbiased ways, we cant have both at the same time )
- [x] modern travis CI setup
- [ ] moving the c code back into haskell
- [x] criterion benchmarks to compare
- [ ] test suite to compare impls
- [ ] test suite to validate determination of stream given several seeds
- [ ] migrating the bad seed mitigation stuff from the Java sibling
- [ ] emailing GUY!!!! (about the splitmix improvement work he's apparently up to, i'll handle this one next weekend)
- [x] doc updates 
- [ ] considering UX changes
- [ ] RandomT?? 
  -  [ ] Should monadic bind do a split (a la quicheck )
- [ ] cleanup big crush stuff and have that as an ancillary library  (does @nkartashov want to own that? its his core work, and its an incredibly valuable tool, though he's busy with grad school and i dont want to impose that on him )

**Comment by idontgetoutmuch** [comment] 2015-12-09 17:07
This is great news.

Do we have the results of the tests written up somewhere?

I had a communication from Guy in April:

"My one recommendation is that you not standardize on a single algorithm.
Rather, make a SplittableRandom type class and provide multiple implementations."

Are we saying that PCG is somehow not as suitable as splitmix? I guess a write up of the tests would help answer this question.

**Comment by cartazio** [comment] 2015-12-09 21:32
Pcg doesn't have a good quality split operator at present.

I do have the basic test run data lying around on my work computer, I just
Got a bit buried this fall, I'll see about digging it up

**Comment by nkartashov** [comment] 2015-12-09 23:27
You are free to use the code in any way you see fit, I'll try to help as much as I can.
@cartazio what parts of C code would you like to move to Haskell? TestU01 code is a mess written in a bad style (global variables, uninformative names etc.), I didn't refactor partly because it had no tests and I could break it without noticing, so I made only patchwork additions.
I moved parts of splitmix to C only for performance, although I cannot claim that my Haskell code is optimal.
@idontgetoutmuch correctness tests can be run using https://github.com/nkartashov/prng-test
btw, if you find any of the tools lacking, I can add you to collaborators, if you like.

**Comment by idontgetoutmuch** [comment] 2016-01-24 18:15
@nkartashov I haven't tried `prng-test` yet but see the issues I have raised for `htestu`. Perhaps I should not be trying `htestu`?

**Comment by nkartashov** [comment] 2016-01-26 16:58
@idontgetoutmuch You mean discard it as a tool?

**Comment by idontgetoutmuch** [comment] 2016-02-18 04:46
See my comment on https://github.com/nkartashov/htestu/issues/2. I am going to find a way we can run all the tests in `htestu` and store the results somewhere. It probably ought to be part of a CI process for RNG.

@cartazio do we have a CI set up? I know very little about how to provide such a thing but I can investigate.

**Comment by idontgetoutmuch** [comment] 2016-02-28 09:33
I have made some small progress e.g. I can now show that passes `smallcrush`:

```
[OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK]
```

But I am having problems using `htestu` at the command line - see: https://github.com/nkartashov/htestu/issues/3.

**Comment by idontgetoutmuch** [comment] 2016-05-05 14:12
I am copying my comments from a closed ticket so they don't get lost.

> It's not ideas that are in short supply. We know we need to a) test the various PRNGs against the various randomness tests (and in particular L'Ecuyers Test01 suite) and b) test their performance.

I have a colleague who is an expert in the field of RNGs but who does not know Haskell. I have created a binding from R to allow him to test their effectiveness https://github.com/idontgetoutmuch/RandomHaskellFromR. I don't think we need a Haskell binding to Test01 (since we can call it from R) but we have one anyway: https://github.com/idontgetoutmuch/RandomHaskellFromR.

One useful thing someone could do would be to create a runnable and repeatable performance test suite maybe using https://github.com/nkartashov/prng-bench but note the issue I raised with it.

My suspicion is that SplitMix will probably be a good replacement but we don't know yet. QuickCheck uses https://hackage.haskell.org/package/tf-random; my testing of it with Test01 shows it passes smallcrush.

If I sound frustrated, it's because I am.

**Comment by cartazio** [comment] 2016-05-05 17:09
We have that code , and we need find the time to clean it up.  I've
scheduled the time this weekend.  Let's synch up after that :)

Or is there other bits I'm overlooking? I was a bit buried under job stuff
this winter and I'm only now climbing back up (eg I did my first new
package to havksge in a while this week ;))

**Comment by Zemyla** [comment] 2016-05-10 15:40
RandomT should not use split like QuickCheck. First off, split can be slow, and splitting for every operation is pretty bad for performance. Second, it means that it violates the monad laws:

```haskell
m >>= return /= m
```

However, it should support using split to feed one half into a calculation and use the other half as the new random state.

**Comment by cartazio** [comment] 2016-05-10 16:23
Split in the splitmix is cheap, agree it's problematic in current random
and tf random.  But let me catchup on stuff and finish getting that branch
up

Also benchmarks :)

**Comment by cchalmers** [comment] 2016-06-17 18:51
> splitmix is the only RNG we know of implemented in haskell that supports a `split` operation that passes big crush when used as the sequencing operation

That's strange, I ran the `c_bigCrush` tests from https://github.com/nkartashov/htestu with `nextStreamFromGen`, `splitNextStreamFromGen` and `leftSplitStreamFromGen` for PCG and it passed them all. Are you where you where using the right generator? (the fast generator would be horrible for splitting, you'd want the multiple sequence generator (the standard one))

Also I recently wrote a [pure Haskell version](http://hackage.haskell.org/package/pcg-random-0.1.3.3/docs/System-Random-PCG-Pure.html) of the standard generator if you're interested.

**Comment by zaxtax** [comment] 2016-06-17 20:09
Is this a pure Haskell version of splitmix?

**Comment by cchalmers** [comment] 2016-06-17 20:15
No, a pure version of multiple sequence variant of PCG (I only had a pure version of the fast variant of PCG before).

**Comment by cartazio** [comment] 2016-06-17 21:50
Derp. Yeah, pcg also did fine.  I think the only piece that was dodgy was the "simulated split " for pcg that didn't use the sequences.  Though I'm not sure if those have the right semantics to line up with how split works for eg split mix

**Comment by idontgetoutmuch** [comment] 2016-08-08 10:17
I uploaded htestu to Hackage: https://hackage.haskell.org/package/htestu. tf-random fails smallcrush when I just tried it contradicting my previous statement. I have reported this failure to the tf-random authors.

We need pcg-random on Hackage and then I can extend the exe that I wrote to use htestu to test it.

**Comment by cchalmers** [comment] 2016-08-08 11:47
@idontgetoutmuch pcg-random is [already on hackage](http://hackage.haskell.org/package/pcg-random).

**Comment by idontgetoutmuch** [comment] 2016-08-08 12:15
Bother! I meant split mix. Thanks.

**Comment by cartazio** [comment] 2016-08-08 13:58
Happy to be validated ;)

I've some work deadlines over the next week or two, then I can prioritize
random and give it some much needed tlc (a bunch of work projects will need
good random tech)

**Comment by idontgetoutmuch** [comment] 2016-12-15 16:56
I have just run [Small
Crush](https://en.wikipedia.org/wiki/TestU01#Features) on a few
Haskell implementations of RNGs. Here are the results. You can run
them yourself if with https://github.com/idontgetoutmuch/htestu.

```
MWC
[OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK]
  Total   time   60.948s  ( 35.058s elapsed)

MT
[OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK]
  Total   time   90.861s  ( 50.819s elapsed)

PCG
[OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK]
  Total   time   57.126s  ( 33.642s elapsed)

TF
[OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK]
  Total   time   86.241s  ( 49.320s elapsed)
```

**Comment by cartazio** [comment] 2016-12-16 05:18
Excellent!

I'll be starting my winter holidays and I'm hoping we can progress some of
the todo items over the next few weeks

**Comment by idontgetoutmuch** [comment] 2017-01-16 18:44
I have discovered more interesting things. If I wrap `System.Random` as a C function and just pass it to the vanilla `C` testu01 suit then it passes SmallCrush. With the Haskell `testu01` package, it apparently fails. The reason is that weirdly `System.Random` has a range of `(1, 2147483562)`. Why would anyone want an RNG that didn’t cover the whole of `Word32` beats me. I attach the output for info. The overhead is prohibitive as you can see so I don’t think we can do this in practice. I have another approach which still allows us to use the vanilla `C` testuo1 suite and is hopefully very fast. I will try that tomorrow.

```
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                 Starting SmallCrush
                 Version: TestU01 1.2.3
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


***********************************************************
HOST = Hogsmill.local, Darwin

MySysRnd


smarsa_BirthdaySpacings test:
-----------------------------------------------
   N =  1,  n = 5000000,  r =  0,    d = 1073741824,    t = 2,    p = 1


      Number of cells = d^t = 1152921504606846976
      Lambda = Poisson mean =      27.1051


----------------------------------------------------
Total expected number = N*Lambda      :      27.11
Total observed number                 :      26
p-value of test                       :    0.53


-----------------------------------------------
CPU time used                    :  00:05:51.02

Generator state:




***********************************************************
Test sknuth_Collision calling smultin_Multinomial

***********************************************************
HOST = Hogsmill.local, Darwin

MySysRnd


smultin_Multinomial test:
-----------------------------------------------
   N =  1,  n = 5000000,  r =  0,   d = 65536,   t =  2,
       Sparse =   TRUE

       GenerCell = smultin_GenerCellSerial
       Number of cells = d^t =         4294967296
       Expected number per cell =  1 /  858.99346
       EColl = n^2 / (2k) =  2910.383046
       Hashing =   TRUE

       Collision test,    Mu =      2909.2534,    Sigma =    53.8957

-----------------------------------------------
Test Results for Collisions

Expected number of collisions = Mu    :     2909.25
Observed number of collisions         :     2919
p-value of test                       :    0.43

-----------------------------
Total number of cells containing j balls

  j =  0                              :       4289970215
  j =  1                              :          4994163
  j =  2                              :             2917
  j =  3                              :                1
  j =  4                              :                0
  j =  5                              :                0

-----------------------------------------------
CPU time used                    :  00:05:51.74

Generator state:




***********************************************************
HOST = Hogsmill.local, Darwin

MySysRnd


sknuth_Gap test:
-----------------------------------------------
   N =  1,  n = 200000,  r = 22,   Alpha =        0,   Beta  = 0.00390625


-----------------------------------------------
Number of degrees of freedom          : 1114
Chi-square statistic                  : 1099.51
p-value of test                       :    0.62

-----------------------------------------------
CPU time used                    :  00:30:04.71

Generator state:




***********************************************************
HOST = Hogsmill.local, Darwin

MySysRnd


sknuth_SimpPoker test:
-----------------------------------------------
   N =  1,  n = 400000,  r = 24,   d =   64,   k =   64


-----------------------------------------------
Number of degrees of freedom          :   19
Chi-square statistic                  :   29.06
p-value of test                       :    0.07

-----------------------------------------------
CPU time used                    :  00:14:59.57

Generator state:




***********************************************************
HOST = Hogsmill.local, Darwin

MySysRnd


sknuth_CouponCollector test:
-----------------------------------------------
   N =  1,  n = 500000,  r = 26,   d =   16


-----------------------------------------------
Number of degrees of freedom          :   44
Chi-square statistic                  :   53.09
p-value of test                       :    0.16

-----------------------------------------------
CPU time used                    :  00:14:32.11

Generator state:




***********************************************************
HOST = Hogsmill.local, Darwin

MySysRnd


sknuth_MaxOft test:
-----------------------------------------------
   N =  1,  n = 2000000,  r =  0,   d = 100000,   t =  6

      Number of categories = 100000
      Expected number per category  = 20.00


-----------------------------------------------
Number of degrees of freedom          : 99999
Chi-square statistic                  :99972.20
p-value of test                       :    0.52


-----------------------------------------------
Anderson-Darling statistic            :    0.65
p-value of test                       :    0.35


-----------------------------------------------
CPU time used                    :  00:06:59.18

Generator state:




***********************************************************
HOST = Hogsmill.local, Darwin

MySysRnd


svaria_WeightDistrib test:
-----------------------------------------------
   N =  1,  n = 200000,  r = 27,  k = 256,  Alpha =      0,  Beta =  0.125


-----------------------------------------------
Number of degrees of freedom          :   41
Chi-square statistic                  :   39.99
p-value of test                       :    0.52

-----------------------------------------------
CPU time used                    :  00:30:04.81

Generator state:




***********************************************************
HOST = Hogsmill.local, Darwin

MySysRnd


smarsa_MatrixRank test:
-----------------------------------------------
   N =  1,  n = 20000,  r = 20,    s = 10,    L = 60,    k = 60


-----------------------------------------------
Number of degrees of freedom          :    3
Chi-square statistic                  :    2.78
p-value of test                       :    0.43

-----------------------------------------------
CPU time used                    :  00:04:14.92

Generator state:




***********************************************************
HOST = Hogsmill.local, Darwin

MySysRnd


sstring_HammingIndep test:
-----------------------------------------------
   N =  1,  n = 500000,  r = 20,   s = 10,   L = 300,   d = 0



Counters with expected numbers >= 10
-----------------------------------------------
Number of degrees of freedom          : 2209
Chi-square statistic                  : 2234.89
p-value of test                       :    0.35

-----------------------------------------------
CPU time used                    :  00:17:34.77

Generator state:




***********************************************************
HOST = Hogsmill.local, Darwin

MySysRnd


swalk_RandomWalk1 test:
-----------------------------------------------
   N =  1,  n = 1000000,  r =  0,   s = 30,   L0 =  150,   L1 =  150



-----------------------------------------------
Test on the values of the Statistic H

Number of degrees of freedom          :   52
ChiSquare statistic                   :   45.87
p-value of test                       :    0.71


-----------------------------------------------
Test on the values of the Statistic M

Number of degrees of freedom          :   52
ChiSquare statistic                   :   55.51
p-value of test                       :    0.34


-----------------------------------------------
Test on the values of the Statistic J

Number of degrees of freedom          :   75
ChiSquare statistic                   :   73.20
p-value of test                       :    0.54


-----------------------------------------------
Test on the values of the Statistic R

Number of degrees of freedom          :   44
ChiSquare statistic                   :   22.99
p-value of test                       :    0.9963


-----------------------------------------------
Test on the values of the Statistic C

Number of degrees of freedom          :   26
ChiSquare statistic                   :   14.98
p-value of test                       :    0.96


-----------------------------------------------
CPU time used                    :  00:02:57.48

Generator state:





========= Summary results of SmallCrush =========

 Version:          TestU01 1.2.3
 Generator:        MySysRnd
 Number of statistics:  15
 Total CPU time:   02:13:10.39

 All tests were passed
```

**Comment by cartazio** [comment] 2017-01-17 21:59
Passing small crush isn't a pass on big crush.

The crux of the issue is making Ye validation tooling faster and able to
run in parallel


Dominic : github let's you attach text files to comments now.  Could you
switch your paste to being an attached text file please?

**Comment by cartazio** [comment] 2017-01-18 01:14
splitmix seems to pass big crush under a few different workloads that matter, see https://github.com/cartazio/random/blob/master/src/System/Random/SplitMix/Internal.hs for my current WIP, wanna also have pcg random and 1-2 other options + a decent entropy initialization in place.

i'm also writing a generalized large fixed size word lib that should optimize well over here https://github.com/cartazio/safeword and may prove helpful

**Comment by idontgetoutmuch** [comment] 2017-01-18 11:30
TF passes SmallCrush :)

[smallCrushTF.txt](https://github.com/haskell/random/files/713731/smallCrushTF.txt)

I have at least two questions:

1. How should we make available the results?
2. How should make it so other folks can reproduce the result?

**Comment by idontgetoutmuch** [comment] 2017-01-18 11:34
Your module only exports `xorShiftR`?

**Comment by idontgetoutmuch** [comment] 2017-01-18 12:15
Yes I know `SmallCrush` does not imply `BigCrush` but we should bear in mind even Mersenne Twister fails `BigCrush` but the R folks and the Python folks use it as the default. I am not saying we should use MT but I am saying that any PRNG can be made to fail some test.

**Comment by cartazio** [comment] 2017-01-26 17:19
I'm reading your test results as saying it fails small crush. 50 standard deviations sounds like failure to me...

**Comment by dschrempf** [comment] 2017-08-24 17:36
Has there been any further development on this issue? I was using StdGen and only after two hours of debugging and looking around online I realized that the cause of my problems was a not so random StdGen. Thank you!

**Comment by cartazio** [comment] 2017-08-24 18:09
I'll be cutting a major version release that's mostly backwards compatible
as 1.3 or something soon.

**Comment by cocreature** [comment] 2018-02-21 20:41
Any progress on this? I’m happy to try and help as my skills (and time) permits!

I think it would be helpful to start by forming a concrete set of TODO items that need to be addressed before we can get the next release and then focus only on those. Otherwise I fear that the trend of more and more ideas creeping into the scope of the next release continues and we won’t see a release in the next two years either.

**Comment by cartazio** [comment] 2018-02-21 22:59
Let’s find a good time to chat on irc over the next 3 days.  I’ll try to
find you when you’re active.  Or leave a set of pms

**Comment by cartazio** [comment] 2018-02-21 23:05
Oops.  Different moritz than the one I thought.

I’ve got 1.2 mostly done on it’s branch in my gh repo.  Just need to figure
out how to split some big breaking changes between several major versions

**Comment by cartazio** [comment] 2018-02-21 23:12
I was stumped on how to have a migrable improvement in the current random
type class without totally breaking every current user.  I’ve some design
ideas I’ll share in the next few days that I think will help

Merrry Wednesday all!

**Comment by idontgetoutmuch** [comment] 2018-02-25 13:38
I am not holding my breath on any substantive progress on this - I think we are coming up to the 3rd birthday of when this issue was raised on the libraries mailing list: https://mail.haskell.org/pipermail/libraries/2015-April/025439.html

I still think this package should be deprecated so at least no-one uses it by accident.

**Comment by zaxtax** [comment] 2018-02-25 13:46
What's the blocker? Why can't we just push something?

**Comment by cartazio** [comment] 2018-02-25 20:34
@zaxtax the last bit I was stuck on (which the friendly inquiries last week prompted me to finally ) was what design to put in an intermediate release that wouldn't be a 100% breaking change for ( existing historical codes).

https://github.com/cartazio/random/tree/v1.2.0 is the current wip, doesn't include some of the cleanup, and i've also been figuring out how to formall characterize the set of types i can give clean semantics too, vs which ones are system / platform dependent. I want samplers to have clear meaning !

**Comment by cartazio** [comment] 2018-02-25 20:37
the system.random api there is mid refactor, because theres a subtle problem with the current api, its not portable between 32 bit and 64bit, and honestly those system dependent types should be under their own interface, at least wrt mathematical sampling code (vs system testing code)

**Comment by cartazio** [comment] 2018-02-25 20:38
(also this thread is strictly for technical discourse, anything else is not constructive, demotivating, and I will delete :) )

**Comment by zaxtax** [comment] 2018-02-25 21:11
How important is it to still support 32bit? Is it possible to cut an
experimental release with just 64bit?

**Comment by cartazio** [comment] 2018-02-25 21:18
@zaxtax  as long as GHC tier 1 platforms include 32bit flavors, pretty important

thats not the actual blocker, even among 32bit platforms, some sizes of types can vary between OSes etc, though in haskell code thats usually isolated to C related types

**Comment by cartazio** [comment] 2018-02-25 21:25
either way, i have a satisfactory story for that issue now, so its now on the top of my oss queue... been buried under type system design work for a bit

**Comment by zaxtax** [comment] 2018-02-25 21:31
Are there any improvements you made that can be pushed out without the big
API refactor?

**Comment by cartazio** [comment] 2018-02-25 21:43
That’s what I’m doing for the 1.2 release.  Stay tuned  :)

**Comment by cartazio** [comment] 2018-02-25 23:33
i'll be pushing periodically  to https://github.com/haskell/random/tree/v1.2.0

**Comment by Bodigrim** [comment] 2020-06-24 21:48
I believe this discussion is obsolete now. Closing.

**Closed by Bodigrim** 2020-06-24 21:48 UTC
